services:
  database:
    image: 'postgres:17.4-alpine3.21'
    environment:
      POSTGRES_PASSWORD: docker
    ports:
      - '15432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: 'atacanet'

volumes:
  postgres_data:
